### ISSUE TITLE
I'm having trouble opening TreeViewer.

### ISSUE THREAD

**Issue by LeilaFattel** [arklumpus/TreeViewer#1]
I just installed TreeViewer on macOS and I keep getting "The action "Run Shell Script" encountered an error. Any suggestions on how to to solve this? Thank you!

**Comment by arklumpus** [comment]
Hi!

1. What version of macOS are you using?
2. Make sure that your security settings let you run programs that come from outside the App Store (go to System Preferences > Security & Privacy > General and make sure that where it says `Allow apps downloaded from` the selected option is `App Store and identified developers`)
2. If you open a terminal, type `TreeViewer`, and press Enter, does anything happen?

**Comment by LeilaFattel** [comment]
Hello!
1. I'm using macOS Sierra v10.12.6
2. I already had set it to that option.
3. I have tried opening TreeViewer through terminal before reaching out, but it did not work.

**Comment by arklumpus** [comment]
Ok, number 1 explains it 😅 Sierra is a very old version of macOS, and it is not supported. You should try to upgrade at least to Catalina (10.15), but if you can Big Sur (11.2+) would probably be better.

I would suggest doing this as soon as possible, not just for TreeViewer, but because by not updating you are missing out on important security patches, and this may put your computer and data in danger!

**Comment by LeilaFattel** [comment]
Okay, it's an easy fix then. Thank you so much!
