### ISSUE TITLE
Undo?

### ISSUE THREAD

**Issue by shlomobl** [arklumpus/TreeViewer#10]
Hi,
I just cannot find it - is there a "undo changes" option?

**Comment by arklumpus** [comment]
Hi! Unfortunately there is no "undo" option as such, currently... If the changes you have made were due to enabling a Plot action or Further transformation module, you can undo them by disabling the module, but otherwise you need to remember which parameters you changed...

This is something I have been thinking about though, I just need to figure out the best way to implement this (i.e., when to create the "snapshots": for example, if you are changing a value using a slider, you wouldn't want the undo option to go back one tick at a time...); hopefully an undo button will appear in the next version!

**Comment by arklumpus** [comment]
Hi, sorry for the long wait, but this is finally implemented in TreeViewer 2.1.0!

You can press `CTRL+Z` (`CMD+Z` on macOS) to undo the last change, or `CTRL+SHIFT+Z` (`CMD+SHIFT+Z` on macOS) to undo the last five changes. After doing this, you can press `CTRL+Y` (`CMD+Y` on macOS) or `CTRL+SHIFT+Y` (`CMD+SHIFT+Y` on macOS) to re-do the changes you had undone. There are also an `Undo` and `Redo` button in the `Edit` tab in the interface.

I am closing this, but feel free to re-open it or to open a new issue if you still have questions!
