### ISSUE TITLE
Plot actions > Highlight node module: how to enable gradient?

### ISSUE THREAD

**Issue by jrom99** [arklumpus/TreeViewer#18]
Hello, I have a rectangular tree and I'd like to set a highlight box from the LCA to the leaves that starts transparent and then ends in a given color. Is it possible to do so with TreeViewer's "Highlight node" module? Many thanks!

## System information:

TreeViewer version 2.2.0
OS: Ubuntu 23.10
DE: GNOME Shell 45.1

**Comment by arklumpus** [comment]
Hi, thank you for your interest in TreeViewer! Unfortunately gradients are not currently supported by this module. It shouldn't be hard to implement this, but I'm currently away from my computer(s)... I will look into it once I get back!

**Comment by arklumpus** [comment]
Hi again, this is now implemented in the _Highlight node_ module (for a single node) and in the _Highlights_ module (for multiple nodes). You should get a notification that an updated module is available today or tomorrow, or you can just install it from the `Module repository` window.

![gradients](https://github.com/arklumpus/TreeViewer/assets/32712606/cdecca2f-e878-45e3-8764-540badec3f53)

Give it a try and let me know what you think, It should be relatively straightforward! You can find some more information below (I will add a more detailed tutorial later on), but it's probably more complicated for me to explain it than for you to actually try it. You can just play a bit with the parameter values...

For a single node, after highlighting it "normally", you can change the `Fill type` to `Gradient` and you will get the options to set up the start and end colours of the gradient, as well as the direction and the position of the midpoint. One thing to note is that, even though the default starting colour is fully transparent, you will need to adjust this as well, when you change the end colour. Otherwise, e.g. a gradient going from fully transparent blue to fully opaque red would look weird.

For the _Highlights_ module, where the highlight colour is determined based on an attribute on the tree, it works the same. You should set the attribute corresponding to the gradient end colour (by default, `Highlight`) to your desired colour, but also the attribute corresponding to the gradient end colour (by default, `HighlightStart`), for the same reason as above.

If you are specifying the values of the `Highlight` as fully opaque hex colour values (`#RRGGBB`), you can use a single _Replace attribute_ module to add `00` (i.e., fully transparent alpha component) to the end of all attributes:
* Set the search `Attribute` to `Highlight`
* Enable the `Regex` checkbox
* Set the search `Value` to `$` (this matches the end of the value)
* Set the replacement `Attribute` to `HighlightStart`
* Set the replacement `Value` to `00` (in this way, `00` will be appended at the end of the attribute value)

**Comment by jrom99** [comment]
It worked wonderfully! Thank you very much!
