### ISSUE TITLE
Crashing when adding attachment to Plot Alignment module

### ISSUE THREAD

**Issue by gabepen** [arklumpus/TreeViewer#45]
I'm on macOS and trying to follow this tutorial https://github.com/arklumpus/TreeViewer/wiki/Drawing-an-alignment-with-the-tree. When I add my fasta file in the Plot Alignment module the program immediately crashes.

**Comment by arklumpus** [comment]
Thanks for sending the files! The problem is that you have two `Vibrio harveyi`, both in the tree and in the alignment. It's not a problem for the tree, but it is for the alignment.

You can solve the issue by removing one of the two sequences, but if you then plot the alignment, the same sequence will be used for both `Vibrio harveyi` entries (which is probably not what you want). My recommendation would be to use something unique for the sequence headers and tip names (e.g., accession numbers), and then store the scientific names in a separate attribute.

In any case, something like this shouldn't cause the program to crash, so thanks for reporting it! I have just pushed an update to the _Plot alignment_ module so that it shows a more useful error message rather than just exploding. You should get an update notification at some point, or you can manually update by opening the `Module repository` (from the `Modules` tab) and looking for the updated module (v1.1.3) the `Plot action` tab.

I hope this helps, let me know you have any other problems!
