### ISSUE TITLE
Exporting through TreeViewerCommandLine taking forever

### ISSUE THREAD

**Issue by lucssantos** [arklumpus/TreeViewer#49]
Hey everyone,

I am working with some big trees throush TreeViewerCommandLine, but when trying to export the tree for visualization it takes 30 minutes or more to do it to pdf or svg format. When trying the png command, the process is killed by the system.

I am trying a ~120k-leaf tree using a laptop with 20 cores and 32GB RAM.

Would that behavior be normal?

**Comment by arklumpus** [comment]
Hi! Even for a tree with 120k leaves, it shouldn't take that long to export the plot... For comparison, I've tried opening the GTDB tree (which contains 107235 leaves), and I'm actually even able to work with it interactively from the GUI (on a Snapdragon laptop running under x64 emulation).

Is this just a plain tree, or do you have much else going on? What OS are you running? Would you be able to send me the tree file to have a look?

**Comment by lucssantos** [comment]
Hi! That's interesting! I am not able to do much interactively from the GUI. 

When exporting, I am trying to do it after applying Branch score style to a tree generated by FastTree. I am using Ubuntu 24.04.

I tried to attach the file here but no success. I sent it to your email, I hope it is not a problem.

**Comment by arklumpus** [comment]
Hi, thanks for sending the tree file! The problem here is likely the Branch score style: when you use this, essentially every branch gets drawn 10 times, which affects plotting times as you may noticed (so that it's as if you were drawing a tree with more than a million leaves).

I would suggest two alternatives:

1. Instead of using the Branch score style, just set the colour attribute of the branches, so that it is determined by the scores.
    <img src="https://github.com/user-attachments/assets/56e3bdb7-7a92-4b80-aa6e-04fb95d660ea" height=300 />
    <details>
    <summary>Commands to create option 1</summary>

    ```
    open PhoU_HMM_SEEDS_trimal.nhx
    y
    attachment add PhoU_HMM.score
    score
    y
    y
    module enable Parse node states
    option select Data file
    option set score
    option select Use first row as header
    option set true
    update
    module enable Propagate attribute
    update
    module enable Branches
    option select Root branch
    option set false
    option select Colour
    option set attribute number score
    option set source viridis.cs
    option select Line weight
    option set 5
    pdf Plot.pdf
    ```

    </details>

2. Leave the branches in the default style, and instead draw coloured shapes at the leaves.
    <img src="https://github.com/user-attachments/assets/2e2e847d-4b5d-414e-9bb7-e2438460604a" height=300 />

    <details>
    <summary>Commands to create option 2</summary>

    ```
    open PhoU_HMM_SEEDS_trimal.nhx
    y
    attachment add PhoU_HMM.score
    score
    y
    y
    module enable Parse node states
    option select Data file
    option set score
    option select Use first row as header
    option set true
    update
    module enable Branches
    option select Root branch
    option set false
    option select Line weight
    option set 5
    module enable Node shapes
    option select Size
    option set 80
    option select Auto fill colour by node
    option set false
    option select Shape
    option set Circle
    option select Fill colour
    option set attribute number score
    option set source viridis.cs
    pdf Plot.pdf
    ```

    </details>

[This ZIP file](https://github.com/user-attachments/files/18200909/viridis.cs.zip) contains the `viridis.cs` file used in the commands (this is the code generated by the TreeViewer GUI when choosing a gradient for the branch colour). It's set up for scores from 0 to 300, but it should be easy to change this (it's line 22 in the `viridis.cs` file).

If you export the tree file using the `nexus` or `binary` commands, you should also be able to open it in the GUI (though it may be a bit painful, depending on your laptop)....

I hope this helps, let me know if you have any questions!

**Comment by lucssantos** [comment]
Thank you for the help. Indeed, using only a single Branches module makes it much faster than before.

**Comment by lucssantos** [comment]
Thank you for the help. Indeed, using only a single Branches module makes it much faster than before.
