### ISSUE TITLE
Citation?

### ISSUE THREAD

**Issue by kevinmyers** [arklumpus/TreeViewer#8]
I want to cite TreeViewer in a manuscript. Is there a citation I should use or just link to the GitHub?

**Comment by arklumpus** [comment]
Hi! Unfortunately we don't have a publication (yet), so for now you can just link the GitHub repository and/or the website [https://treeviewer.org](https://treeviewer.org).

I will make sure to add a Zenodo DOI when I release the next update to TreeViewer. If you have not finished your manuscript by then you could use that; otherwise, just a link should be sufficient.

I will leave this issue open until we have the DOI.

**Comment by kevinmyers** [comment]
Sounds good. Thanks for the quick reply! We really love using TreeViewer - it's a great program!

**Comment by arklumpus** [comment]
Hi, sorry for the long wait! I have finally created a new release, and I have a Zenodo DOI (which is shown on the homepage of https://treeviewer.org and in this repository). Do not worry if it is too late, but it would be great if you could cite it if you use TreeViewer in the future!

I am closing this, feel free to reopen or to open another issue if you still have questions!
